data:
  type: "pointcloud"
  data_dir: "/../../data/concept_shapenet/"
  save_dir: "/../../data/models/"
  results_dir: "/../../data/results/"
  seed: 0
train:
  num_epochs: 50
  learning_rate: 0.0003
  batch_size: 64
  num_workers: 16
  network:
    pointnet_radius: 0.5
    pointnet_nclusters: 512
    scale: 1
    in_features: 2