data:
  type: "rawstate"
  data_dir: "/../../data/concept_shapenet/"
  save_dir: "/../../data/models/"
  results_dir: "/../../data/results/"
  seed: 0
train:
  num_epochs: 100
  learning_rate: 0.01
  batch_size: 32
  num_workers: 16
  network:
    nb_layers: 3
    nb_units: 256