data:
  type: "rgb"
  data_dir: "/../../data/concept_shapenet/"
  save_dir: "/../../data/models/"
  seed: 0
train:
  num_epochs: 50
  learning_rate: 0.001
  batch_size: 32
  num_workers: 16
  network:
    input_dim: 1
    frozen: True